name: YouTube Upload Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (adjust if needed)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create cookies.txt
        run: echo "${{ secrets.YOUTUBE_COOKIES }}" > youtube.com_cookies.txt
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Run upload bot
        run: python main.py
